### ISSUE TITLE
7월 2주차 스터디 내용입니다.(2020-07-06 ~ 2020-07-12)

### ISSUE THREAD

**Issue by Quska45** [seokyoung-kim/TripleS-server#1]
1. 회원가입 / 로그인 개발
 - 회원가입 / 로그인은 구글, 네이버의 서버에서 처리되고 우리 시스템은 리턴 값만을 받는다.
 - 우리는 리턴값을 디비에 저장하고 관리하는 식으로 유저에 대한 기능을 사용한다.
 - 네이버, 구글 서버에서 리턴해주는 토큰은 인증을 위해 사용된다.
 - 현재 정해진 방향성에 대한 검증과 잘못된 부분이 있다면 개선될 필요가 있다.

2. 우리 시스템 flow chart확인하기
 - url : https://www.figma.com/file/gPNYIjoTOWMr8dVoDQuBVf/TripleS?node-id=60%3A65

3. 슬랙 / 깃허브 활용
 - 슬랙 : 정보공유가 필요한 내용에 대해 슬랙을 활용한다.
 - 깃허브 : 일정관리에 활용한다.
 - 깃허브의 projects 기능은 서버 레파지토리에서 관리한다.

4. 백엔드 서버 패키지 구조 리팩토링
 - 필요하다고 생각되는 방향성에 대해 생각하고 구체화 하기

5. 몽고디비 서버
 - 의진이형이 헤로쿠 통해 생성하고 공유

6. 소스 관리
 - 석영이형의 마스터 레파지토리에서 각자의 브랜치를 만들고 dev에 머지하고 마스터에 머지 하는 식으로 개발 진행

7. 다음주 까지 개발 목표
 - 공통사항 : 기능 목록 정의(우리 시스템에 필요한 기능이 뭐가 있는 지에 대해서 생각해보고 정리)
 - 프론트 : 기획 + 로그인 기능 완료
 - 서버 : 크롤링 개발 방식 통일 및 데이터 크롤링 완료
  - 패키지 구조 정리
  - 데이터 크롤링
  - 크롤링된 데이터 디비에 저장
  - 스캐줄러 개발

**Comment by WonYong-Jang** [comment]
1. 사용자가 로그인 진행 시 프론트에서 네이버 및 구글 로그인을 선택하면 해당 api로 이동하여 인증 토큰을 받아서 로그인 및 회원가입을 진행하는데 
인증 진행하는 부분이 정해진게 있나요? ( Oauth2, 또는 JWT )

다른 항목은 pull request로 확인 부탁드려요

**Comment by Quska45** [comment]
스터디 시간에 제가 이해한 내용이 정확하다면 서버에서는 인증과 관련된 처리를 하지 않습니다.(인증과 관련된 처리를 하지 않는다는게 정확한 표현인지 모르겠네요 ㅠㅠ. 부족한 부분에 대해서 다른 분들이 추가적으로 설명해주시면 좋겠습니다.)
 - 인증과 관련된 부분은 프론트에서 전부 처리하고 백엔드로 토큰을 비롯한 정보(아이디 등)을 request 합니다. 
 - 백앤드에서는 프론트에서 requst로 전달받은 토큰을 세션에 가지고 있다가 프론트에서 추가적인 request가 발생 했을 때 인증과 관련된 처리를 하는데 사용하고 나머지 정보는 상항에 맞게 사용하게 됩니다.

**Comment by justwaves** [comment]
소셜 로그인 방식은 공부가 더 필요해서 스터디 시간에는 확실하게 정해진 건 없었어요. 
그래서 제가 계속 공부를 하고 있고 자세한건 정리해서 스터디 시간에 말씀드릴텐데 일단 간략하게 설명하자면

기본적인 소셜 로그인 방식은 (네이버 예시)
1. 클라이언트에서 네이버 로그인 버튼을 누르면 네이버 로그인 페이지가 보여짐
2. 로그인에 성공하면 네이버에서 발행한  access token과 함께 지정해 놓은 콜백 URL로 이동
3. 네이버에서 보내준 access token으로  다시 회원 정보(email, name, id 등)를 네이버에 요청
4. 받은 회원정보(id or email)를 통해서 서버에서 회원가입 or 로그인 처리 (이 부분부터는 일반적인 JWT 인증 과정과 같음)
5. 인증이 되면 JWT를 발행해서 프론트로 보내줌
6. 프론트에서는 그 토큰을 헤더나 쿠키에 담아서 인증 처리

이런 방식으로 진행되고 보통 3번 부분을 서버에서 처리하는 게 일반적인 것 같은데 
네이버로그인 가이드 문서에서 자바스크립트 부분을 따라하거나
리액트 라이브러리(구글로그인, 네이버로그인 둘 다)를 사용하면 
회원정보를 받는 것까지 프론트에서 다 처리가 되더라고요
그래서 저번 스터디 시간에 서버에서 인증 처리를 안해도 될 것 같다고 말한거고요
근데 이렇게하면 보안에 문제가 있을 것 같아서 더 알아보고 있어요

지금 회원정보 받는 것까지 프론트에서 구현을 해놓긴 했는데 이 방법으로 그냥 할 지
아니면 서버에서 회원정보를 받아오는 걸로 바꿀 지 정해야 할 것 같아요
