### ISSUE TITLE
잡 실행관련해서 봐주셨으면 하는게 있습니다 ㅠㅠ

### ISSUE THREAD

**Issue by Quska45** [seokyoung-kim/TripleS-server#5]
제가 만든 BrunchJob을 CrawlingScheduler에 추가하지 않았는데 job이 실행이 됩니다. 
제가 Quartz에 대한 학습이 안되어 있긴한데 소스 구조상 CrawlingScheduler에 내가 만든 job을 추가했을 때 실행되는 것이 정상적인 것 같은데 이상하다고 생각됩니다.
쉽게 갈려고 했는데 결국엔 Quartz에 대해서 모르고는 넘어갈 수가 없겠네요 ㅠㅠ
공부하면서 이유는 찾아보겠지만 혹시 이것과 관련해서 이유가 생각나신다면 답변주세요!
가능하시면 dev.bkj2 브랜치 확인해 주시면 감사하겠습니다!

**Comment by WonYong-Jang** [comment]
CrawlingScheduler에 대해 설명이 부족했던 것같아ㅠㅠ
쿼츠 스케줄러는 JobDetail과 트리거로 동작하고
JobDetail은 우리가 각각 만든 job의 정보들이 들어감 (job 이름, 클래스 등등 )
트리거는 job이 실행될 시간을 작성하는 것이고 소스가 반복되서 함수로 빼놨어 ( buildCronJobTrigger )

JobDetail에는 현재 job테스트를 위해서 FestaJob을 3개 연달아서 만들어놓고 스케줄러에 등록해서 brunchJob을 
등록안했는데도 돌아가고 있는 것같아!
아래 소스가 JobDetail을 만들고 있고 

```
JobDataMap jobDataMap1 = new JobDataMap();
        jobDataMap1.put("JobName","Job Chain 1"); // JobName 을 Job Chain 1 로 지정
        JobDetail jobDetail = JobBuilder.newJob(FestaJob.class).usingJobData(jobDataMap1).build();
```

아래가 스케줄러에 등록하는 소스인데 소스 모두 주석처리하면 스케줄러는 동작하지 않을 거 같은데 
확인하고 다시 답 부탁해~

`scheduler.scheduleJob(jobDetail, buildCronJobTrigger("3 * * * * ?"));`


```
/**
 *
 * @description : Job 을 정해진 시간에 실행 하도록 설정 ( Crawling Scheduler )
 */
@Component
@RequiredArgsConstructor
public class CrawlingScheduler {

    private final Scheduler scheduler;

    @PostConstruct
    public void start() throws SchedulerException, InterruptedException {
        
        JobDataMap jobDataMap1 = new JobDataMap();
        jobDataMap1.put("JobName","Job Chain 1"); // JobName 을 Job Chain 1 로 지정
        JobDetail jobDetail = JobBuilder.newJob(FestaJob.class).usingJobData(jobDataMap1).build();

        JobDataMap jobDataMap2 = new JobDataMap();
        jobDataMap2.put("JobName","Job Chain 2");
        JobDetail jobDetail2 = JobBuilder.newJob(FestaJob.class).usingJobData(jobDataMap2).build();

        JobDataMap jobDataMap3 = new JobDataMap();
        jobDataMap3.put("JobName","Job Chain 3");
        JobDetail jobDetail3 = JobBuilder.newJob(FestaJob.class).usingJobData(jobDataMap3).build();

        scheduler.scheduleJob(jobDetail, buildCronJobTrigger("3 * * * * ?"));
        scheduler.scheduleJob(jobDetail2, buildCronJobTrigger("3 * * * * ?"));
        scheduler.scheduleJob(jobDetail3, buildCronJobTrigger("3 * * * * ?"));


        Thread.sleep(3 * 1000);  // Job이 실행될 수 있는 시간 여유를 준다

    }

    /**
     * @param scheduleExp ( cron 표현식 )
     * @Description Trigger 생성 함수
     * @return : Trigger ( Job을 실행 시킬 스케줄링 조건 )
     * // *  *  *  *  *  *  *
     * // 초 분  시 일  월 요일 년도(생략가능)
     */
    public Trigger buildCronJobTrigger(String scheduleExp) {
        return TriggerBuilder.newTrigger().withSchedule(CronScheduleBuilder.cronSchedule(scheduleExp))
                .build();

        //        startAt과 endAt을 사용해 job 스케쥴의 시작, 종료 시간도 지정할 수 있다.
        //        Trigger trigger = TriggerBuilder.newTrigger().startAt(startDateTime).endAt(EndDateTime)
        //                .withSchedule(CronScheduleBuilder.cronSchedule("*/1 * * * *")).build();
    }
}
```

**Comment by Quska45** [comment]
결론 부터 얘기하면 문제는 해결 했습니다! 근데 제가 생각하기엔 잡을 등록하는 부분에서 문제가 있는게 아니라 의존성 주입에서 문제가 있는 것 같습니다. 읽어보시고 답변 부탁 드려요!
형 얘기 해주신 대로 잡을 주석 처리해보면서 테스트 해봤습니다. 전부 주석하면 당연히 스캐줄러가 동작하지 않았는데 하나를 주석하든 두개를 주석하든 계속 feataJob이 아니라 brunchJob이 실행됐습니다.
그래서 생각이 든게 저희가 ICrawling이라는 인터페이스를 사용하고 각자 ICrawling에 대해 구현을 해서 사용하는데, 의존성 주입을 해주는 부분에서 따로 id를 지정해 주지 않아서 클래스 순서에 따라 먼저 빈등록이되는 brunchJob을 주입받아서 사용하는게 아닐까 싶었습니다. 
그래서 festa의 소스를 다음과 같이 수정하고 실행했을 때 festaJob이 실행되는 결과를 얻을 수 있었습니다. 그리고 brunchJob은 실행되지 않았고 제가 스캐줄러 클래스에 잡을 추가했을 때만 실행되는 결과도 얻을 수 있었습니다.
```
@Component("festaCrawling")
@RequiredArgsConstructor
public class FestaCrawling implements ICrawling {
 ...
}
```
```
@Slf4j
@RequiredArgsConstructor
public class FestaJob extends QuartzJobBean implements InterruptableJob {

    private final ICardDao cardDao;
    private final ICrawling crawling;

    ...
}
```
따라서 잡등록의 문제가 아니라 의존성주입에서 문제가 있었던게 아닐까 싶습니다.
혹시 제가 틀렸거나 다른 생각이 있으시면 코멘트 부탁 드리겠습니다!

**Comment by WonYong-Jang** [comment]
위에서 말해준것 처럼 의존성 주입에 문제가 있는게 맞는 것 같네!
ICrawling crawling은 ICrawling 타입에 맞는 빈을 주입하게 되는데
여러 job들이 동일한 타입을 인터페이스 받아서 구현하게 되고
올려준 소스에 brunchJob에 @Primary 어노테이션이 선언되어 있어서 같은 타입중에 제일 먼저 DI 되는것 같네 

이해가 안가는 부분은 @Component를 지정하면 자동으로 클래스 이름이 빈 id가 되는 걸로 알고 있어서
brunchCrawling 와 festaCrawling는 각각 id는 다르지만 ICrawling이라는 같은 타입의 빈이 생성되고
아래 소스 FestaJob 에서 ICrawling 을 DI할때 id를 정확하게 지정해줘야 해결될 것 같은데
혹시 제가 잘못 알고 있는지 석영형도 같이 확인 부탁드려요!

```
public class FestaJob extends QuartzJobBean implements InterruptableJob {

    private final ICardDao cardDao;
    private final ICrawling crawling; // 여기서 변경해줘야 하는 ??? ???????????

    ...
}

```


아래와 같이 변경해서 저도 다시 테스트 해볼께요 
```

@Slf4j
@RequiredArgsConstructor
public class FestaJob extends QuartzJobBean implements InterruptableJob {

    private final ICardDao cardDao;
     @Qualifier("festaCrawling;")
    @Autowired
    private ICrawling festaCrawling;

    ...
}
```

또는

```
public class FestaJob extends QuartzJobBean implements InterruptableJob {

    private final ICardDao cardDao;
    private final ICrawling festaCrawling; // 변수 이름을 맞춰주기 

```
 
> 참고 url : https://www.podo-dev.com/blogs/224

**Comment by Quska45** [comment]
넵 저는 형 얘기 해주신게 맞는 것 같습니다. 참고 url도 확인했습니다.
